spacex_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: admin
      port: 5432
      dbname: spacex_raw
      schema: silver
      threads: 4
    clickhouse:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: dbt
      password: 'dbt_password'
      schema: gold
      secure: False
      threads: 4